apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-quality-project.fullname" . }}
  labels:
    {{- include "aiops-quality-project.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aiops-quality-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aiops-quality-project.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GITHUB_WEBHOOK_URL
              value: {{ .Values.env.GITHUB_WEBHOOK_URL | quote }}
            - name: GITHUB_TOKEN
              value: {{ .Values.env.GITHUB_TOKEN | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}