replicaCount: 1

image:
  # URL репозиторію ECR буде вставлено GitHub Actions
  repository: 865683084473.dkr.ecr.eu-west-2.amazonaws.com/goit-mlops-repo
  pullPolicy: IfNotPresent
  # Тег буде оновлено автоматично GitHub Actions
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

# Змінні оточення для нашого FastAPI сервісу
env:
  # GITHUB_WEBHOOK_URL: "https://api.github.com/repos/YOUR_USERNAME/YOUR_REPO/dispatches"
  GITHUB_WEBHOOK_URL: "REPO_WEBHOOK_URL"
  # GITHUB_TOKEN: "токен з репозиторію"
  GITHUB_TOKEN: "GH_PAT"

# Анотації для Prometheus, щоб він знав, що треба скрейпити цей под
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"  # Порт, на якому FastAPI віддає метрики
  prometheus.io/path: "/metrics"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi